### ISSUE TITLE
original database files to create qiime artefacts

### ISSUE THREAD

**Issue by rderelle** [marcomeola/DAIRYdb#2]
Hi,

using the Qiime artefacts, I got the following error message:
`DAIRYdb_v1.2.0.qza was created by 'QIIME 2018.11.0'. The currently installed framework cannot interpret archive version '5'.`

It seems I have to create de novo qiime artefacts because the qiime version I have is not the same as the one you have used to build them.

To do so, would it be possible to have access to the database files 'DAIRYdb_v1.2.0_ok.fasta' and 'DDB_taxonomy.txt' mentioned in the Readme ?
I couldn't find them (my apologies if I missed them).

many thanks
Romain

**Comment by marcomeola** [comment]
Hi Romain,
thanks for your message. 
@erifa1 can you generate the DAIRYdb with the latest qiime version?

**Comment by rderelle** [comment]
Hi Marco,

thanks for your reply.

The thing is that I'm using an older version of Qiime (qiime2-2018.8), and I would like to not modify my setup to not create incompatibilities between my projects.

Therefore, would it be possible to release the original database files (sequences and taxonomy) so that anybody could create qiime artefact using its own Qiime version ?

best,
Romain

**Comment by marcomeola** [comment]
You can find the fasta file of the database in the IDTAXA or METAXA folders along with the tax file. Eventually you need to wrangle around the tax structure for qiime. Hope that helps you

**Comment by rderelle** [comment]
many thanks for the tips.
all good.

What worked for me (in case someone had the same issue):
_ file DAIRYdb_v1.2.0_20190222_blast.fasta in BLAST folder
_ file DAIRYdb_v1.2.0_20190222_TAX.txt in Metaxa2 folder

you just need to add a line 'Feature ID	Taxon' at the beginning of the taxonomy file.

**Comment by rderelle** [comment]
Edit:
the import was working fine but not the classifier.

For the classifier to work, you would need to perform these 2 additional modifications:
 _ remove all '>' from the taxonomy file (-> same names in fasta and taxonomy files)
 _ remove the end of the 2 sequences NR_121699 and CP016439 in the fasta file (weird characters not recognised by Qiime classifier)

hope that helps
