### ISSUE TITLE
Additional species for v.1.2.5

### ISSUE THREAD

**Issue by marcomeola** [marcomeola/DAIRYdb#3]
Streptococcus orisratti (Accession AF124350)

**Comment by marcomeola** [comment]
add type strain of all Streptococcus species

**Comment by erifa1** [comment]
#4: List of redundant sequences to investigate

**Comment by marcomeola** [comment]
Lactococcus laudensis
Leuconostoc rapi
Romboutsia timonensis
Romboutsia lituseburensis
Leuconostoc citreum (remove AM157444 and FJ859696) check Type Strain 16S
Brevibacterium antiquum
