### ISSUE TITLE
Identical sequences different taxonomy

### ISSUE THREAD

**Issue by felipelira** [marcomeola/DAIRYdb#4]
Using a local script to create a non-redundant database I found, between other examples, that two different IDs present identical sequences.

Could you help me with this?

The sequences IDs are:
>NR_025618.1 Streptomyces olivaceiscleroticus strain DSM 40595 16S ribosomal RNA, partial sequence
>NR_025619.1 Streptomyces niger strain DSM 43049 16S ribosomal RNA, partial sequence

Attached file:

[identical_Sequences.txt](https://github.com/marcomeola/DAIRYdb/files/5912632/identical_Sequences.txt)

Kind regards,
Felipe

**Comment by erifa1** [comment]
Dear Felipe, 

Thanks for opening this issue. Some taxa can have the same 16S sequences making them difficult to differentiate. If you found others taxa presenting identical sequences, could you please list their IDs here? This will help and we can take it in account in the next update. 

For the moment, if you need the unique sequences of the DAIRYdb, you can use dereplication tools like vsearch. 

Regards
Etienne

**Comment by felipelira** [comment]
Dear Etienne, 

In this manner, at leas in my opinion, identical 16S would be represented by unique species or represented at the higher level (for example, genus, family...). Thank you for the suggestion of vsearch. It is nice for huge datasets. For a small dataset as yours, a simple python script can solve this without biases related to the % of identity of clustered sequences.

I searched for identical sequences in your own database without check the taxonomy to see if they correspond or if they are really different. I give you the floor for you ; ) 

the script I used is here: [(https://github.com/felipelira/python/blob/master/nr.py)]

Reach me back if you have any questions or when the updated database is available.

[redundant_Seqs.txt](https://github.com/marcomeola/DAIRYdb/files/5918290/redundant_Seqs.txt)



Explaining the attached file, each line was extracted from the .fasta file. Each identifier between '[ ]' corresponds to the first ID after the '>'.

**Comment by erifa1** [comment]
These IDs you found are not in DAIRYdb. Are they from your own dataset? 

I effectively see 15 sequences presenting more than one unique ID.  
```bash
sed '1d' DAIRYdb_v1.2.4_20200221_OK.csv|cut -f22|sort|uniq -c|sort -nr|grep 2|wc -l
15
```

Thanks to your nr.py program, we have those 15 sequences presenting different IDs. 

```
>Psychrobacter_Species_AY007244 Psychrobacter_arcticus_AY444822_TS redundseq
>Streptococcus_uberis_AM946015 Streptococcus_vestibularis_AY188353_TS redundseq
>Bacillus_stratosphericus_AJ831841_TS Bacillus_aerophilus_AJ831844_TS redundseq
>Salinispira_pacifica_KC665949_TS Salinispira_pacifica_CP006939 redundseq
>Lactobacillus_hilgardii_ACGP01000200_TS Lactobacillus_buchneri_ACGH01000101_TS redundseq
>Stenotrophomonas_Species_AE005673 Xanthomonas_campestris_AE008922_TS redundseq
>Brachybacterium_rhamnosum_AJ415376_TS Brachybacterium_sacelli_AJ415384_TS redundseq
>Oerskovia_paurometabola_AJ314851_TS Corynebacterium_freneyi_AJ292762_TS redundseq
>Sphingobacterium_daejeonense_LN651153 Sphingobacterium_mizutaii_AJ438175_TS redundseq
>Obesumbacterium_proteus_AJ233422_TS Ignatzschineria_larvae_AJ252143_TS redundseq
>Pseudomonas_umsongensis_AF468450_TS Pseudomonas_Species_AF465411 redundseq
>Arthrobacter_tumbae_AJ315069_TS Citricoccus_muralis_AJ344143_TS redundseq
>Glutamicibacter_bergerei_AJ609630_TS Glutamicibacter_nicotianae_KM878200 redundseq
>Glutamicibacter_arilaitensis_KR001877 Glutamicibacter_mysorens_AJ617482_TS redundseq
>Yersinia_kristensenii_AF366381_TS Yersinia_rohdei_AF366384_TS redundseq
```

We will investigate this for the next update.

Thanks again 
Regards 
Etienne




For your information I had an error: 
```
Traceback (most recent call last):
  File "nr.py", line 24, in <module>
    print(">" + v[0] + " " + v[1:] + " redund") # + "[" + v[1:] + "]")
TypeError: must be str, not list
```
I used 
```python3
print(">" + v[0] + " " + " ".join(v[1:]) + " redundseq") 
```

**Comment by felipelira** [comment]
Thank you for your return, Etienne.

I modified the script because I tried to check if there were more than two IDs in the case they were redundant too.

Cheers, 
Felipe
