### ISSUE TITLE
Database format for Nanoclust pipeline

### ISSUE THREAD

**Issue by luciauy** [marcomeola/DAIRYdb#5]
I wanted to use your DAIRYdb database in my 16S pipeline analysis using Nanoclust (https://www.biorxiv.org/content/10.1101/2020.05.14.087353v1). I am working with Nanopore data. 
Do you have this kind of format?

**Comment by erifa1** [comment]
Dear luciauy
Thanks for opening this issue. Nanoclust is using blast for taxonomic assignment. You can find the blast-formatted DAIRYdb in `DAIRYdb_v1.2.4_20200604/DAIRYdb_v1.2.4_20200604_blast/`. 
Let us know if it works fine with Nanoclust. 
Regards. 
Etienne

**Comment by ghost** [comment]
Hi everyone.
Tried to use SILVA as a database for my 16s pipeline (nanopore data). I managed to transform SILVA into the bastdb format. However, is there a way to convert the SILVA format into the taxdb which is requested for the nanoclust run ?

**Comment by erifa1** [comment]
Hi
Commit [16dcb35](https://github.com/marcomeola/DAIRYdb/commit/16dcb353d3565be815acf9b8a4b49594143cd8c8) on nanoclust_db dev branch is the formatted ddb for nanoclust. It works with Nanoclust but needs some improvement (missing taxids). 
It is a blast formatted database with the last version of blast (see https://www.ncbi.nlm.nih.gov/books/NBK279688/).
I used taxonkit tools to determine taxid based on the taxa names.

Etienne
